---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(plotly)
library(shiny)


pivot_data <- read.csv("/Users/gabrielburcea/Rprojects/data/PivotMappe060520r.csv", header = TRUE, sep = ",")
cities <- readr::read_rds("/Users/gabrielburcea/Rprojects/data/cities.rds")


pivot_data$gender <- as.factor(pivot_data$Gender)
pivot_data$country <- as.factor(pivot_data$Country)
pivot_data$location <- as.factor(pivot_data$Location)
pivot_data$chills <- as.factor(pivot_data$Chills)
pivot_data$cough  <- as.factor(pivot_data$Cough)
pivot_data$diarrhoea  <- as.factor(pivot_data$Diarrhoea)
pivot_data$fatigue  <- as.factor(pivot_data$Fatigue)
pivot_data$headache   <- as.factor(pivot_data$Headcahe)
pivot_data$loss_smell_taste   <- as.factor(pivot_data$Loss.of.smell.and.taste)
pivot_data$muscle_ache  <- as.factor(pivot_data$Muscle.Ache)
pivot_data$nasal_congestion <- as.factor(pivot_data$Nasal.Congestion)
pivot_data$nausea_vomiting  <- as.factor(pivot_data$Nausea.and.Vomiting)
pivot_data$self_diagnosis <- as.factor(pivot_data$Self.Diagnosis)
pivot_data$shortness_breath <- as.factor(pivot_data$Shortness.of.Breath)
pivot_data$sore_throat <- as.factor(pivot_data$Sore.Throat)
pivot_data$sputum <- as.factor(pivot_data$Sputum)
pivot_data$temperature  <- as.factor(pivot_data$Temperature)
pivot_data$health_care_worker <- as.factor(pivot_data$Healthcare.Worker)
pivot_data$care_home_worker <- as.factor(pivot_data$Care.Home.Worker)


level_key_chills <-
  c( 'Yes' = "Chills",
     'No' = "No",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_cough <-
  c( 'Yes' = "Cough",
     'No' = "No",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_diarrhoea <-
  c( 'No' = "No",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_fatigue <-
  c( 'No' = "No",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_headache <-
  c('No' = "No",
    'Yes' = "Mild",
    'Yes' = "Moderate",
    'Yes' = "Severe",
    'Yes' = "Headcahe")
level_key_loss_smell_taste <-
  c( 'No' = "Loss of smell and taste",
     'No' = "No",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_muschle_ache <-
  c( 'No' = "No",
     'No' = "Muscle Ache",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_nasal_congestion <-
  c( 'No' = "No",
     'No' = "Nasal Congestion",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_nausea_vomiting <-
  c( 'No' = "No",
     'Yes' = "Nausea and Vomiting",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_self_diagnosis <-
  c( 'No' = "None",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_short_breath <-
  c( 'No' = "No",
     'No' = "Shortness of Breath",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_sore_throat <-
  c( 'No' = "No",
     'No' = "Sore Throat",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_sputum <-
  c( 'No' = "No",
     'No' = "Sputum",
     'Yes' = "Mild",
     'Yes' = "Moderate",
     'Yes' = "Severe")
level_key_care_home_worker <-
  c('Yes' = 'Yes',
    'No' = 'No')




#### Refactor the levels ##################################################
data_not_sev <- pivot_data %>%
  dplyr::mutate(chills = forcats::fct_recode(chills, !!!level_key_chills),
                cough = forcats::fct_recode(cough, !!!level_key_cough),
                diarrhoea = forcats::fct_recode(diarrhoea, !!!level_key_diarrhoea),
                fatigue = forcats::fct_recode(fatigue, !!!level_key_fatigue),
                headache = forcats::fct_recode(headache, !!!level_key_headache),
                loss_smell_taste = forcats::fct_recode(loss_smell_taste, !!!level_key_loss_smell_taste),
                muscle_ache = forcats::fct_recode(muscle_ache, !!!level_key_muschle_ache),
                nasal_congestion = forcats::fct_recode(nasal_congestion, !!!level_key_nasal_congestion),
                nausea_vomiting = forcats::fct_recode(nausea_vomiting, !!!level_key_nausea_vomiting),
                self_diagnosis = forcats::fct_recode(self_diagnosis, !!!level_key_self_diagnosis),
                shortness_breath = forcats::fct_recode(shortness_breath, !!!level_key_short_breath),
                sore_throat = forcats::fct_recode(sore_throat, !!!level_key_sore_throat),
               # temperature = forcats::fct_recode(temperature, !!!level_key_temperature),
                sputum = forcats::fct_recode(sputum, !!!level_key_sputum)) %>%
  dplyr::select(ID, country, location, chills, cough, diarrhoea, fatigue, headache, loss_smell_taste, muscle_ache, nasal_congestion, 
               nausea_vomiting, shortness_breath, sore_throat, sputum, temperature)



gather_divided <- data_not_sev %>%
  tidyr::pivot_longer(cols=4:16, names_to="Symptom", values_to="Severity") %>%
  dplyr::filter(Severity!="No") %>%
  dplyr::group_by(Symptom, country, location) %>%
  tally()



geoloc_cities_numbers <- dplyr::left_join(gather_divided, cities) %>% 
  tidyr::drop_na() %>% 
  group_by(Symptom, location, country, lon, lat) %>% 
  dplyr::summarise(Count = n())




library(choroplethr)
library(plotly)

# light grey boundaries
l <- list(color = plotly::toRGB("grey"), width = 0.5)

#specify map projection/options

g <- list(
  
  showframe = FALSE, 
  showcoastlines = FALSE, 
  projection = list(type = 'Mercator')
  
)


fig <- plot_geo(geoloc_cities_numbers)

fig

fig <- fig %>% plotly::add_trace(
  z = ~Count, color = ~Count, colors = "Blues", 
  text = ~country, location = ~location, marker = list(line = 1)
)

fig
#fig <- fig %>% colorbar(title = "SARS-COVID-19 Symptoms by Country")

# fig <- fig %>% layout(title = 'Symptom by Country<br>Source:<a Your.md Data', 
#                       geo = g)
# 
# fig

```





Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# light grey boundaries
l <- list(color = plotly::toRGB("grey"), width = 0.5)

#specify map projection/options

g <- list(
  
  showframe = FALSE, 
  showcoastlines = FALSE, 
  projection = list(type = 'Mercator')
  
)


fig <- plot_geo(geoloc_cities_numbers)

fig

fig <- fig %>% plotly::add_trace(
  z = ~Count, color = ~Count, colors = "Blues", 
  text = ~country, location = ~location, marker = list(line = 1)
)

fig <- fig %>% colorbar(title = "SARS-COVID-19 Symptoms by Country", tickprefix = '$')

fig <- fig %>% layout(title = 'Symptom by Country<br>Source:<a Your.md Data', 
                      geo = g)

fig
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

